Task_1


In [ ]:
import numpy as np

def array_factory(mode: str, shape, value=None):
    """
    this function genrate arrays such as:
    - 'zeros': Array filled with 0.
    - 'ones': Array filled with 1.
    - 'full': Array filled with a specified 'value'.
    - 'identity': A square identity matrix of size 'shape'.
    """
    try:
        if mode == "zeros":
            return np.zeros(shape)

        elif mode == "ones":
            return np.ones(shape)

        elif mode == "full":
            return np.full(shape, value)

        elif mode == "identity":
            return np.eye(shape)

        else:
            raise ValueError(f"Invalid mode: {mode}")

    except (TypeError, ValueError) as e:
        raise ValueError(f"Invalid array operation: {e}")

In [ ]:

print(array_factory(input("Select one modle:zeros\nones\nfull\nidentity"),5))

[0. 0. 0. 0. 0.]


Task_2

In [24]:
import numpy as np

def secure_reshape_and_stack(data1, data2, new_shape):
    """
    this function Converts two datasets into NumPy arrays, reshapes the first dataset,and vertically stacks it with the second dataset.

    Parameters:
        data1: The first dataset to be converted and reshaped.
        data2: The second dataset to be converted into a NumPy array.
        new_shape: The target shape for reshaping the first dataset.

    Returns:
        A NumPy array containing both datasets vertically stacked.

    
    """

    try:
        # Convert inputs to ndarray to ensure they are processed as Tensors
        # arr = np.array(data1)

        arr1 = np.array(data1)
        arr2 = np.array(data2)

        # Rule: Change the shape of arr1 to new_shape
        # Common usage: turning a vector (1D) into a matrix (2D) by using reshape function
        reshaped_arr1 = arr1.reshape(new_shape)

        # Rule: Vertical Stacking (vstack)
        # Requirement: Both matrices must have the same number of columns
        combined_dataset = np.vstack((reshaped_arr1,arr2))

        return combined_dataset

    except ValueError as e:
        # Handle cases where reshape size doesn't match or stack columns don't match
        raise ValueError(f"Company-grade Error: {e}")

In [25]:
data1 = [1, 2, 3, 4, 5, 6]
data2 = [[7, 8, 9], [10, 11, 12]]

result = secure_reshape_and_stack(data1, data2, (2, 3))

print(result)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
