In [ ]:
pip install numpy

In [3]:
import numpy as np

In [4]:
v = np.array([1,2,3])
m= np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

In [5]:
s = np.array(5)

In [ ]:
print(s.ndim)
print(v.ndim)
print(m.ndim)

print(s.shape)
print(v.shape)
print(m.shape)

0
1
2
()
(3,)
(3, 3)


In [15]:
class Studente:
    def __init__(self,name):
        self._name = name

    @property
    def name(self):
        return self._name
    @name.setattr
    def name (self,name):
        self._name = name

AttributeError: 'property' object has no attribute 'setattr'

In [16]:
s1 = Studente("Osama")
s1.name
s1.name = "ali"


AttributeError: property 'name' of 'Studente' object has no setter

In [ ]:
vec = np.array([1,2,3,4,5,6])
mar = vec.reshape((3,2))
mar

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
vec = np.array([1,2,3,4])
vec.shape[0]
mat = vec.reshape((vec.shape[0],1))
mat


array([[1],
       [2],
       [3],
       [4]])

In [27]:
vec = np.array([1,2,3,4])
vec.shape[0]
mat = vec[:,None]
mat

array([[1],
       [2],
       [3],
       [4]])

In [22]:
m= np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
m.shape[1]

3

In [ ]:
def arra(arr , row : int = -1 ,col : int = -1 ):
    try:
        arr= np.array(arr)
        return arr.reshape(row , col)
    except (TypeError , ValueError) as e:
        raise ValueError (f"Invalid reshape :{e}")

lis = [1,2,3,4,5]
print(arra(lis))

In [56]:
class c:
    x=3
o=c()
ma = np.array([[1.2,"5",3],
                [4,5,6],
                [7,8,9]])
# ma.dtype

fmat=ma.astype(np.float64)
print(fmat.dtype)
ma


float64


array([['1.2', '5', '3'],
       ['4', '5', '6'],
       ['7', '8', '9']], dtype='<U32')

In [42]:
mat = np.array([[1.2,2,3],
                [4,5,6],
                [7,8,9]])
mar.dtype

dtype('int64')