In [1]:
import numpy as np 


In [30]:
s = np.array(5)
print(s)
print("========")

v = np.array([1,2,3,4,5,6])
print(v)
print("========")
m = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(m)

5
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
s = np.array(5)
print(s.ndim)
print(s.shape)

print("========")

v = np.array([1,2,3,4,5,6])
print(v.ndim)
print(v.shape)

print("========")
m = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(m.ndim)
print(m.shape)


0
()
1
(6,)
2
(3, 3)


In [2]:
vec = np.array([1,2,3,4,5,6])
mat = vec.reshape((3,2))
mat
# print(mat.shape[1])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
vec = np.array([1,2,3,4])
mat = vec.reshape((vec.shape[0], 1))
print(mat)

[[1]
 [2]
 [3]
 [4]]


In [39]:
vec = np.array([1,2,3,4])
vec[:, None]

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
vec = np.array([1,2,3,4])
mat = vec.reshape((vec.shape[0], 1))
print(mat)

In [ ]:
def array_reshape(arr: list, rows:int = -1, cols:int =-1):
    
    try:
        arr = np.array(arr)
        return arr.reshape(rows,cols)
    except (TypeError, ValueError) as e:
        raise ValueError(f"Invalid reshape operation:{e}")

In [7]:
vec = [1,2,3,4,5,6]
array_reshape(vec, 2)

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
class c:
    x =3
o1 = c()   

In [56]:
m = np.array([[o1,2,'3'],
              [True,5,6],
              [7,8,9]])
print(m.dtype)
print(m)

object
[[<__main__.c object at 0x00000224B6BEA570> 2 '3']
 [True 5 6]
 [7 8 9]]


In [66]:
m = np.array([[1,2,'3'],
              [4,5,6],
              [7,8,9]])
fmat = m.astype(float)
print(fmat)
print(fmat.dtype)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
float64


In [73]:
m = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [0,0,0]])
v = np.array([3,2,5,1])
m[-3:-1, -3:-1]

array([[4, 5],
       [7, 8]])

In [ ]:
mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
matT= mat.T
matT


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [79]:
mat = np.full((3,4),5)
mat

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])